# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main", "dev/*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: | 
              python -m pip install --upgrade pip
              pip install -r requirements.txt

      - name: Unit test
        run: python -m unittest discover -s tests/unit_tests -p '*_test.py'
